"""Rule definition for ~そうだ (hearsay/reported speech & appearance/likelihood)"""

from kotogram.grammar import GrammarRule, GrammarRulePattern, TokenPattern
from kotogram.patterns import CommonPatterns
from kotogram.types import InflectionForm, InflectionType, PartOfSpeech, POSDetailType


def create_rule() -> GrammarRule:
    """Create the ~そうだ grammar rule (combines hearsay and appearance meanings)"""
    return GrammarRule(
        name="~そうだ",
        patterns=[
            # Hearsay patterns (伝聞)
            GrammarRulePattern(
                patterns=[
                    *CommonPatterns.VERB_OR_I_ADJ_PLAIN,
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
            GrammarRulePattern(
                patterns=[
                    *CommonPatterns.NA_ADJ_STEM_NA_OR_DEARU,
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
            GrammarRulePattern(
                patterns=[
                    TokenPattern(
                        part_of_speech=PartOfSpeech.NOUN,
                        pos_detail=POSDetailType.NOUN_ADJECTIVE_VERBAL_STEM,
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だっ"),
                            TokenPattern(value="だ"),
                        ],
                    ),
                    TokenPattern(
                        value="た",
                        optional=True,
                    ),
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
            GrammarRulePattern(
                patterns=[
                    TokenPattern(part_of_speech=PartOfSpeech.NOUN),
                    TokenPattern(value="だ"),
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
            # Appearance patterns (様態)
            GrammarRulePattern(
                patterns=[
                    TokenPattern(
                        part_of_speech=PartOfSpeech.VERB,
                        infl_form=InflectionForm.INFLECTED,
                    ),
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="な"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
            GrammarRulePattern(
                patterns=[
                    TokenPattern(
                        part_of_speech=PartOfSpeech.ADJECTIVE,
                        infl_type=InflectionType.ADJECTIVE_ISTEM,
                    ),
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="な"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
            GrammarRulePattern(
                patterns=[
                    TokenPattern(
                        part_of_speech=PartOfSpeech.NOUN,
                        pos_detail=POSDetailType.NOUN_ADJECTIVE_VERBAL_STEM,
                    ),
                    TokenPattern(
                        value="そう",
                    ),
                    TokenPattern(
                        part_of_speech=PartOfSpeech.AUXILIARY_VERB,
                        alternatives=[
                            TokenPattern(value="だ"),
                            TokenPattern(value="な"),
                            TokenPattern(value="です"),
                        ],
                    ),
                ]
            ),
        ],
        description="動詞普通形/い形容詞普通形＋そうだ\nな形容詞普通形＋そうだ\n名詞＋だ＋そうだ\n動詞「ます形」＋そうだ\nい形容詞語幹＋そうだ\nな形容詞語幹＋そうだ",
        category="N4",
        index=4,
        examples=[
            # Hearsay examples
            "来週うちの近くでお祭りがあるそうです。",
            "友だちによると、去年の試験は簡単だったそうです。",
            "友だちの話では新しい辞書はとてもいいそうです。",
            # Appearance examples
            "山田先生はいつも難しそうな本を読んでいます。",
            "石田さんが忙しそうだから、手伝いましょう。",
            "ポケットから財布が落ちそうだよ。",
        ],
    )
